SAP_AR_TABLES = {
"KNA1": "Stores general customer master data, including customer identification, names, addresses, communication details, classification, search terms, international location numbers, authorization groups, one-time account indicators, and record creation metadata. This information is valid across the entire SAP system and is not specific to any company code or sales area.",
"KNB1": "Contains company code-specific customer data such as accounting information (GL and reconciliation accounts), payment terms and methods, dunning procedures, credit management settings, tax classification, house bank details, payment block information, personnel number connections, alternative payer information, and account statement parameters. Enables financial processing and reporting per company code.",
"KNVV": "Holds sales area-specific customer data, including sales organization, distribution channel, division, pricing procedures, shipping conditions, delivery priorities, order processing parameters, sales document types, billing schedules, Incoterms, customer statistics groups, and sales-specific blocks and indicators.",
"KNBK": "Stores customer bank details required for payment transactions, such as bank country key, bank identifier/routing numbers, bank account numbers, control keys, partner types, account holder information, IBAN, SWIFT/BIC details, and payment method mappings.",
"KNVH": "Manages customer hierarchy information, allowing definition of parent-child relationships between customers, hierarchy types, hierarchical levels, validity periods, sales organizational assignments, and higher-level customer references for reporting and pricing purposes.",
"KNVP": "Contains partner function assignments for customers, including partner function codes, partner type assignments, sales area associations, partner counter references, related customer or vendor numbers, personnel connections, default partner indicators, contact person linkages, and validity periods.",
"KNVS": "Stores shipping-specific data for customers, including shipping point assignments, transportation zones and routes, shipping conditions, delivery priorities, forwarding agent connections, goods receiving hours, loading point specifications, transportation scheduling parameters, and Incoterms.",
"KNVK": "Maintains details of individual contact persons associated with each customer, such as contact identification numbers, names, titles, departments, roles, communication details, language preferences, primary contact indicators, and position/function information.",
"KNVI": "Holds customer tax-related information, including departure country codes, tax category assignments, customer tax classifications, VAT registration numbers, tax exemption data, withholding tax parameters, tax jurisdiction codes, and tax reporting requirements."
}
MODULE_TABLES = {"AR" : SAP_AR_TABLES}